[2022-03-23 08:02:01,981] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2022-03-23T07:00:00+00:00 [queued]>
[2022-03-23 08:02:02,047] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2022-03-23T07:00:00+00:00 [queued]>
[2022-03-23 08:02:02,048] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 08:02:02,048] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2022-03-23 08:02:02,049] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 08:02:02,212] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2022-03-23T07:00:00+00:00
[2022-03-23 08:02:02,219] {standard_task_runner.py:53} INFO - Started process 4441 to run task
[2022-03-23 08:02:02,523] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2022-03-23T07:00:00+00:00 [running]> DESKTOP-NRCNVOU.localdomain
[2022-03-23 08:02:02,647] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: 'C:\\Users\\Dan\\airflow\\secrets\\keyfile.json'
Traceback (most recent call last):
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/operators/gcs_to_bq.py", line 246, in execute
    conn = bq_hook.get_conn()
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 68, in get_conn
    service = self.get_service()
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 82, in get_service
    http_authorized = self._authorize()
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/gcp_api_base_hook.py", line 193, in _authorize
    credentials = self._get_credentials()
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/gcp_api_base_hook.py", line 154, in _get_credentials
    google.oauth2.service_account.Credentials.from_service_account_file(
  File "/home/collid/.local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 238, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/collid/.local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dan\\airflow\\secrets\\keyfile.json'
[2022-03-23 08:02:02,653] {taskinstance.py:1189} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=load_data, execution_date=20220323T070000, start_date=20220323T080201, end_date=20220323T080202
[2022-03-23 08:02:11,837] {logging_mixin.py:112} INFO - [2022-03-23 08:02:11,836] {local_task_job.py:103} INFO - Task exited with return code 1
